### Signup User
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "asdf@momo.com",
  "password": "asdlfkajsd"
}

### Login User
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "asdf@bogo.com",
  "password": "asdlfkajsd"
}

### WHOAMI
GET  http://localhost:3000/auth/whoami


### Logout
POST  http://localhost:3000/auth/signout


### Get All Users
GET http://localhost:3000/auth
Content-Type: application/json


### Update User
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "dono@mama.com"
}